import Head from 'next/head'
import styles from '../../styles/pages/Staking.module.scss'

import SmallBackground from '../../components/SmallBackground'

import { Pie, Line } from 'react-chartjs-2';


export default function Staking() {

  const data = canvas => {
    const ctx = canvas.getContext('2d');
 
    let gradientBlack = ctx.createLinearGradient(500, 0, 100, 0);
    gradientBlack.addColorStop(0, '#3B2E5D');
    gradientBlack.addColorStop(1, '#271A49');

    let gradientGreen = ctx.createLinearGradient(500, 0, 100, 0);
    gradientGreen.addColorStop(0, '#4DF6A4');
    gradientGreen.addColorStop(1, '#1BC472'); 

    return {
      labels: ['Red', 'Blue'],
    datasets: [
      {
        label: '# of Votes',
        data: [75,25],
        backgroundColor: [
          gradientGreen,
          gradientBlack,          
        ],
        borderColor: [
          gradientGreen,
          gradientBlack,       
        ],
        borderWidth: 1,
      },
    ],
  }
  };
    

  return (
 <>
      <Head>
        <title>Loterra - Staking</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SmallBackground/>
         <div className={styles.container}>
          <div className="w4">
          <Pie data={data} />

          </div>
          <div className="w8">
            <div className="lota-card">
                <div className={styles.card_header}>
                  <h1>Staking</h1>
                  <h2>Unstake or stake your LOTA in order to get rewards and voting weight</h2>
                </div>
                <div className={styles.card_form}>
                  <input type="text" placeholder="Amount"/>
                    <div className="w4">
                      <i>MAX</i>                      
                      <button className="plain">Stake</button>
                      <span>Available: 100LOTA</span>
                    </div>
                    <div className="w4">
                      <i>MAX</i>                      
                      <button className="plain">Unstake</button>
                      <span>Available: 100LOTA</span>
                    </div>
                    <div className="w4">      
                      <i></i>                                     
                      <button className="plain">Claim unstake</button>
                      <span>Available: 100LOTA</span>
                    </div>
                </div>
            </div>
          </div>
          <div className="w12">
            <div className="lota-card mt-3">
              <div className="w6">
              <Line data={data} />
              </div>
              <div className="w6 center">
                  <div className={styles.card_header}>
                  <h1>Staking rewards</h1>
                  <h2>Claim what is yours, or perhaps another nice sentence</h2>
                  </div>
                  <button className="pink">Claim rewards</button>
              </div>
            </div>
          </div>
        </div>
   
    </>
  )
}
