import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/pages/Staking.module.scss'

export default function Staking() {

    

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <a href="/">Go back</a>
    
      </main>

     
    </div>
  )
}
