import Head from 'next/head'
import styles from '../../styles/pages/Dao.module.scss'
import {  Line } from 'react-chartjs-2';
import { Plus } from "phosphor-react";

import React from 'react';

import SmallBackground from '../../components/SmallBackground'
import ProposalModal from '../../components/ProposalModal'

export default function Dao() {

  const proposals = [1,2,3,4,5,6]

  const [modalIsOpen,setIsOpen] = React.useState(false);

    
  const lineOptions = {
    
    scales:{
      xAxis:{
        beginAtZero:true,
        display:false
      },
      yAxis:{
        beginAtZero:true,
        display:false 
      },
      },
    plugins : {
  
      legend: {
        display: false
    },
    title: {
        display: false
    }
    },
    
}


const lineData_green = canvas => {

  const ctx = canvas.getContext('2d');  
  let gradientGreen = ctx.createLinearGradient(0, 0, 0, 170);
  gradientGreen.addColorStop(0, '#193250');
  gradientGreen.addColorStop(1, '#181446'); 



  return {
    labels: [75,25,10,21,35,40,77],
 
  datasets: [
    {      
      data: [75,25,10,21,35,40,77],
      fill:true,
      backgroundColor:gradientGreen,
      borderColor: [
        '#20FF93',   
      ],
      pointBackgroundColor: '#20FF93',
      pointBorderColor: '#FFFFFF',
      pointBorderWidth: 2,
      lineTension: .4,
      borderWidth: 4,
    },
  ],

}
};
  

  const lineData = canvas => {

    const ctx = canvas.getContext('2d');  
    let gradientPink = ctx.createLinearGradient(0, 0, 0, 170);
    gradientPink.addColorStop(0, '#431166');
    gradientPink.addColorStop(1, '#1F0A49'); 



    return {
      labels: [75,25,10,21,35,40,77],
   
    datasets: [
      {      
        data: [75,25,10,21,35,40,77],
        fill:true,
        backgroundColor:gradientPink,
        borderColor: [
          '#FF36FF',   
        ],
        pointBackgroundColor: '#FF36FF',
        pointBorderColor: '#FFFFFF',
        pointBorderWidth: 2,
        lineTension: .4,
        borderWidth: 4,
      },
    ],
  
  }
  };

  return (
    <>
    <Head>
    <title>Loterra - DAO</title>
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <SmallBackground/>
     <div className={styles.container}>
        <div className="w12">
          <div className="lota-card">
            <div className="w12">
              <h1>Staking</h1>
            </div>
              <div className="w4">
                <h4>Tickets gold average</h4>
                <div className={styles.chart}>               
                    <Line data={lineData} options={lineOptions}/>
                </div>
              </div>
              <div className="w4">
                <h4>Players average</h4>
                <div className={styles.chart}>               
                    <Line data={lineData} options={lineOptions}/>
                </div>
              </div>
              <div className="w4">
                <h4>Number of winners</h4>
                <div className={styles.chart}>               
                    <Line data={lineData} options={lineOptions}/>
                </div>
              </div>
              <div className="w4">
                <h4>Jackpot</h4>
                <div className={styles.chart}>               
                    <Line data={lineData} options={lineOptions}/>
                </div>
              </div>        
          </div>
        </div>
        <div className="w12 mt-3">
          <div className="lota-card">
            <div className="w12">
              <h1>Total stats</h1>
            </div>
              <div className="w6">
                <h4>Tickets sold</h4>
                <div className={styles.chart}>               
                    <Line data={lineData_green} options={lineOptions}/>
                </div>
              </div>
              <div className="w6">
                <h4>Players</h4>
                <div className={styles.chart}>               
                    <Line data={lineData_green} options={lineOptions}/>
                </div>
              </div>                  
          </div>
        </div>
        <div className="w12 mt-3">
          <div className="lota-card">
            <div className="w12">
              <h1>Proposals</h1>
              <button className={'plain ' + styles.add_proposals} onClick={() => setIsOpen(!modalIsOpen)}>Create proposal <Plus size={18}/></button>
            </div>
                { proposals.map( (obj) => {
                    return (
                      <div className="base-card mt-2">
                  <div className="w12">
                      <h3 className="fb">Proposal 15</h3>
                      <p className="desc">New upcoming design for LoTerra frontend interface preview here https://drive.google.com/file/d/1JDVwEVQLjQSASunLgb6rXu2QPvvEm2k3/view?usp=drivesdk</p>
                  </div>
                  <div className="w8">
                      <div className="w6"><p><strong>Creator</strong></p></div>
                      <div className="w6"><p>terra1ar45r5e8y55ku847xvet6ny2psv6fkflhchzxk</p></div>
                      <div className="w6"><p><strong>End block height</strong></p></div>
                      <div className="w6"><p>3371352</p></div>
                      <div className="w6"><p><strong>Amount</strong></p></div>
                      <div className="w6"><p>50</p></div>
                      <div className="w6"><p><strong>Status</strong></p></div>
                      <div className="w6"><p>Passed</p></div>
                      <div className="w6"><p><strong>Price per rank</strong></p></div>
                      <div className="w6"><p>[]</p></div>
                      <div className="w6"><p><strong>Proposal</strong></p></div>
                      <div className="w6"><p>DaoFunding</p></div>
                      <div className="w6"><p><strong>Yes votes</strong></p></div>
                      <div className="w6"><p>2</p></div>
                      <div className="w6"><p><strong>No votes</strong></p></div>
                      <div className="w6"><p>0</p></div>
                  </div>
                  <div className="w4">
                    <div className="plain-card center">                      
                            <h4 className="fb mt-1 mb-1">Vote</h4>                       
                            <div className="w6"><button className="plain fm mb-2">Yes</button></div>
                            <div className="w6"><button className="plain fm mb-2">No</button></div>
                    </div>
                  </div>
                </div>
                    )
                })}
          </div>
        </div>
        <ProposalModal data={modalIsOpen} click={()=>setIsOpen(!modalIsOpen)}/>
      </div>
      
    </>
  )
}
