import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/pages/Dao.module.scss'

export default function Dao() {

    

  return (
    <div className={styles.container}>
      <Head>
        <title>Loterra - DAO</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <a href="/">Go back</a>
    
      </main>

     
    </div>
  )
}
